// QB Brain entry: every module only declares things at load time; init() calls run the app in this order.
import { init as init_config } from "./config.js";
import { init as init_store } from "./store.js";
import { init as init_menubg } from "./menubg.js";
import { init as init_plays } from "./plays.js";
import { init as init_myplays } from "./myplays.js";
import { init as init_paths } from "./paths.js";
import { init as init_state } from "./state.js";
import { init as init_setup } from "./setup.js";
import { init as init_canvas } from "./canvas.js";
import { init as init_rep } from "./rep.js";
import { init as init_defense } from "./defense.js";
import { init as init_loop } from "./loop.js";
import { init as init_draw } from "./draw.js";
import { init as init_sound } from "./sound.js";
import { init as init_fx } from "./fx.js";
import { init as init_sprites } from "./sprites.js";
import { init as init_input } from "./input.js";
import { init as init_evaluate } from "./evaluate.js";
import { init as init_drive } from "./drive.js";
import { init as init_summary } from "./summary.js";
import { init as init_train } from "./train.js";
import { init as init_keyread } from "./keyread.js";
import { init as init_playbook } from "./playbook.js";
import { init as init_coach } from "./coach.js";
import { init as init_film } from "./film.js";
import { init as init_profile } from "./profile.js";
import { init as init_learn } from "./learn.js";
import { init as init_progress } from "./progress.js";
import { init as init_dashboard } from "./dashboard.js";
import { init as init_results } from "./results.js";
import { init as init_pro } from "./pro.js";
import { init as init_cloud } from "./cloud.js";
import { init as init_account } from "./account.js";
import { installTestHooks } from "./testhooks.js";

init_config();
init_store();
init_plays();
init_myplays();
init_paths();
init_state();
init_setup();
init_canvas();
init_rep();
init_defense();
init_loop();
init_draw();
init_sound();
init_fx();
init_sprites();
init_input();
init_evaluate();
init_drive();
init_summary();
init_train();
init_keyread();
init_playbook();
init_coach();
init_film();
init_profile();
init_progress();
init_dashboard();
init_results();
init_pro();
init_learn();
init_menubg();
// Parent accounts + cloud sync are built but switched off for the beta (package.json → "features").
// eslint-disable-next-line no-undef
if(__QB_FEATURES__.accounts){ init_cloud(); init_account(); }
installTestHooks();
